version: '3.3'

services:
  down-alerting-bot:
    container_name: down-alerting-bot
    restart: always
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db:rw

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    depends_on:
      - mongo

